from extensions import db
from datetime import datetime, timezone
import json

class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(20), nullable=False)
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    candidate = db.relationship("Candidate", backref="user", uselist=False, lazy=True)
    company = db.relationship("Company", backref="user", uselist=False, lazy=True)

class Candidate(db.Model):
    __tablename__ = "candidates"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, unique=True)
    full_name = db.Column(db.String(255))
    phone = db.Column(db.String(50))
    location = db.Column(db.String(255))
    headline = db.Column(db.String(500))
    years_of_experience = db.Column(db.Float, default=0)
    current_role = db.Column(db.String(255))
    current_company = db.Column(db.String(255))
    education = db.Column(db.Text)
    skills = db.Column(db.Text)
    linkedin_url = db.Column(db.String(500))
    portfolio_url = db.Column(db.String(500))
    avatar_url = db.Column(db.String(500))
    bio = db.Column(db.Text)

class Company(db.Model):
    __tablename__ = "companies"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, unique=True)
    company_name = db.Column(db.String(255), nullable=False)
    industry = db.Column(db.String(255))
    website = db.Column(db.String(500))
    location = db.Column(db.String(255))
    company_size = db.Column(db.String(50))
    description = db.Column(db.Text)
    logo_url = db.Column(db.String(500))
    contact_person = db.Column(db.String(255))
    contact_phone = db.Column(db.String(50))

class Job(db.Model):
    __tablename__ = "jobs"
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey("companies.id"), nullable=False)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    responsibilities = db.Column(db.Text)
    qualifications = db.Column(db.Text)
    required_skills = db.Column(db.Text)
    preferred_skills = db.Column(db.Text)
    location = db.Column(db.String(255))
    employment_type = db.Column(db.String(50))
    experience_level = db.Column(db.String(50))
    min_experience_years = db.Column(db.Float, default=0)
    salary_min = db.Column(db.Float)
    salary_max = db.Column(db.Float)
    remote_allowed = db.Column(db.Boolean, default=False)
    status = db.Column(db.String(20), default="open")
    ats_weight_skills = db.Column(db.Integer, default=40)
    ats_weight_experience = db.Column(db.Integer, default=25)
    ats_weight_projects = db.Column(db.Integer, default=15)
    ats_weight_certifications = db.Column(db.Integer, default=10)
    ats_weight_keywords = db.Column(db.Integer, default=10)
    ats_pass_threshold = db.Column(db.Integer, default=70)
    interview_pass_threshold = db.Column(db.Integer, default=70)
    final_hiring_threshold = db.Column(db.Integer, default=80)
    application_deadline = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    company = db.relationship("Company", backref="jobs", lazy=True)
    resumes = db.relationship("Resume", backref="job", lazy=True)

class Resume(db.Model):
    __tablename__ = "resumes"
    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(db.Integer, db.ForeignKey("candidates.id"), nullable=False)
    job_id = db.Column(db.Integer, db.ForeignKey("jobs.id"), nullable=True)
    original_filename = db.Column(db.String(255))
    stored_filename = db.Column(db.String(255))
    file_path = db.Column(db.String(500))
    file_size = db.Column(db.Integer)
    mime_type = db.Column(db.String(50))
    raw_text = db.Column(db.Text)
    extracted_skills = db.Column(db.Text)
    extracted_experience_years = db.Column(db.Float)
    extracted_education = db.Column(db.Text)
    extracted_email = db.Column(db.String(255))
    extracted_phone = db.Column(db.String(50))
    ats_score = db.Column(db.Float)
    skill_match_score = db.Column(db.Float)
    experience_match_score = db.Column(db.Float)
    keyword_match_score = db.Column(db.Float)
    project_match_score = db.Column(db.Float)
    certification_match_score = db.Column(db.Float)
    matched_skills = db.Column(db.Text)
    missing_skills = db.Column(db.Text)
    recommendations = db.Column(db.Text)
    status = db.Column(db.String(20), default="uploaded")
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    candidate = db.relationship("Candidate", backref="resumes", lazy=True)
    parsed_data = db.relationship("ParsedResumeData", backref="resume", uselist=False, lazy=True)

class ParsedResumeData(db.Model):
    __tablename__ = "parsed_resume_data"
    id = db.Column(db.Integer, primary_key=True)
    resume_id = db.Column(db.Integer, db.ForeignKey("resumes.id"), nullable=False, unique=True)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255))
    phone = db.Column(db.String(50))
    date_of_birth = db.Column(db.String(50))
    location = db.Column(db.String(255))
    nationality = db.Column(db.String(100))
    linkedin = db.Column(db.String(500))
    github = db.Column(db.String(500))
    portfolio = db.Column(db.String(500))
    kaggle = db.Column(db.String(500))
    stackoverflow = db.Column(db.String(500))
    summary = db.Column(db.Text)
    skills = db.Column(db.Text)
    languages = db.Column(db.Text)
    awards = db.Column(db.Text)
    good_words = db.Column(db.Text)
    experience = db.Column(db.Text)
    education = db.Column(db.Text)
    projects = db.Column(db.Text)
    certifications = db.Column(db.Text)
    action_word_count = db.Column(db.Integer)
    ats_score = db.Column(db.Float)
    resume_strength_score = db.Column(db.Integer)
    category = db.Column(db.String(100))
    parsing_error = db.Column(db.Text)

class Interview(db.Model):
    __tablename__ = "interviews"
    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(db.Integer, db.ForeignKey("candidates.id"), nullable=False)
    job_id = db.Column(db.Integer, db.ForeignKey("jobs.id"))
    resume_id = db.Column(db.Integer, db.ForeignKey("resumes.id"))
    total_questions = db.Column(db.Integer, default=0)
    answered_questions = db.Column(db.Integer, default=0)
    skipped_questions = db.Column(db.Integer, default=0)
    overall_score = db.Column(db.Float)
    communication_score = db.Column(db.Float)
    technical_score = db.Column(db.Float)
    confidence_score = db.Column(db.Float)
    feedback = db.Column(db.Text)
    strengths = db.Column(db.Text)
    weaknesses = db.Column(db.Text)
    recommendation = db.Column(db.String(50))
    recording_path = db.Column(db.String(500))
    transcript_path = db.Column(db.String(500))
    status = db.Column(db.String(20), default="in_progress")
    started_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = db.Column(db.DateTime)

    candidate = db.relationship("Candidate", backref="interviews", lazy=True)
    job = db.relationship("Job", backref="interviews", lazy=True)
    questions = db.relationship("InterviewQuestion", backref="interview", lazy=True)

class InterviewQuestion(db.Model):
    __tablename__ = "interview_questions"
    id = db.Column(db.Integer, primary_key=True)
    interview_id = db.Column(db.Integer, db.ForeignKey("interviews.id"), nullable=False)
    order_index = db.Column(db.Integer)
    question_type = db.Column(db.String(50))
    difficulty = db.Column(db.String(20))
    question_text = db.Column(db.Text)
    follow_up = db.Column(db.Text)
    expected_keywords = db.Column(db.Text)
    expected_concepts = db.Column(db.Text)
    reference = db.Column(db.Text)
    answer_text = db.Column(db.Text)
    answer_audio_path = db.Column(db.String(500))
    answered_at = db.Column(db.DateTime)
    answer_duration = db.Column(db.Integer)
    score = db.Column(db.Float)
    technical_accuracy = db.Column(db.Float)
    completeness = db.Column(db.Float)
    depth = db.Column(db.Float)
    communication = db.Column(db.Float)
    confidence = db.Column(db.Float)
    relevance = db.Column(db.Float)
    semantic_score = db.Column(db.Float)
    keyword_score = db.Column(db.Float)
    feedback = db.Column(db.Text)
    strengths = db.Column(db.Text)
    weaknesses = db.Column(db.Text)
